package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccThemeDataSource(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: `data "authsignal_theme" "theme" {}`,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "name", "dev management api tests"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "logo_url", "https://res.cloudinary.com/authsignal/image/upload/v1716774524/m7bvgqjzr29tp69qcogr.png"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "favicon_url", "https://res.cloudinary.com/authsignal/image/upload/v1716774530/nvjzmbqax2jiiwse3a40.png"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "watermark_url", "https://res.cloudinary.com/authsignal/image/upload/v1716774530/nvjzmbqax2jiiwse3a40.jpg"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "primary_color", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "borders.button_border_radius", "1"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "borders.button_border_width", "2"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "borders.card_border_radius", "3"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "borders.card_border_width", "4"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "borders.input_border_radius", "5"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "borders.input_border_width", "6"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "borders.container_border_radius", "7"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.button_primary_text", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.button_primary_border", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.button_secondary_text", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.button_secondary_background", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.button_secondary_border", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.card_background", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.card_border", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.input_background", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.input_border", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.link", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.heading_text", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.body_text", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.container_background", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.container_border", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.divider", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.icon", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.loader", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.positive", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.critical", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.information", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.hover", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "colors.focus", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "page_background.background_color", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "page_background.background_image_url", "https://res.cloudinary.com/authsignal/image/upload/v1716774650/scn2dj1eqvpg9uxuffsr.png"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "container.content_alignment", "left"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "container.padding", "1"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "container.logo_alignment", "center"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "container.logo_position", "inside"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "container.logo_height", "2"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "container.position", "outside"),

					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.logo_url", "https://res.cloudinary.com/authsignal/image/upload/v1716774524/m7bvgqjzr29tp69qcogr.png"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.favicon_url", "https://res.cloudinary.com/authsignal/image/upload/v1716774530/nvjzmbqax2jiiwse3a40.png"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.watermark_url", "https://res.cloudinary.com/authsignal/image/upload/v1716774530/nvjzmbqax2jiiwse3a40.jpg"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.primary_color", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.borders.button_border_radius", "1"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.borders.button_border_width", "2"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.borders.card_border_radius", "3"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.borders.card_border_width", "4"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.borders.input_border_radius", "5"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.borders.input_border_width", "6"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.borders.container_border_radius", "7"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.button_primary_text", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.button_primary_border", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.button_secondary_text", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.button_secondary_background", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.button_secondary_border", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.card_background", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.card_border", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.input_background", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.input_border", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.link", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.heading_text", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.body_text", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.container_background", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.container_border", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.divider", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.icon", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.loader", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.positive", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.critical", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.information", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.hover", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.colors.focus", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.page_background.background_color", "#ABCD12"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.page_background.background_image_url", "https://res.cloudinary.com/authsignal/image/upload/v1716774650/scn2dj1eqvpg9uxuffsr.png"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.container.content_alignment", "left"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.container.padding", "1"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.container.logo_alignment", "center"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.container.logo_position", "inside"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.container.logo_height", "2"),
					resource.TestCheckResourceAttr("data.authsignal_theme.theme", "dark_mode.container.position", "outside"),
				),
			},
		},
	})
}
